name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint Lua Scripts
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: iLLeniumStudios/fivem-lua-lint-action@v1-backticks
        with:
          capture: "junit.xml"
          args: "-t --formatter JUnit"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: "**/junit.xml"
          fail_on_failure: 0
